27718 : CRITICAL : Assertion failed: pytrace_event_handler:434: (!"Unexpected pytrace start") : . Please contact the technical support.  
